/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PROG02;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new ThreadWithExtends("T1").start();
        Runnable run = new ThreadWithImplements();
        new Thread(run,"T2").start();
    }
}
