/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PROG02;

import java.util.concurrent.TimeUnit;

public class ThreadExecute {
    public String getGreeting() {
        return "Hello World!";
    }

    public synchronized void threadExecute() {
       //new ThreadWithExtends("Kerosene").start();
        //ThreadWithExtends threadWithExtends = new ThreadWithExtends("Test01");
        //threadWithExtends.start();

        //Runnable run = new ThreadWithImplements();
        //new Thread(new ThreadWithImplements(),"Oxygen").start();
        //Runnable run = new ThreadWithImplements();
        //Thread thread = new Thread(new ThreadWithImplements(),"Oxygen");
        //thread.start();
        //thread.interrupt();
        //if(thread.isInterrupted()){

          //  System.out.println("I got Interrupted");
       // }

      // System.out.println(Thread.currentThread().getId());
        Thread thread = new Thread(new ThreadWithImplements(),"Oxygen");
         ThreadWithExtends  threadWithExtends = new ThreadWithExtends("Kerosene");
         thread.start();
         threadWithExtends.start();

        try { TimeUnit.SECONDS.sleep(1);
        } catch(InterruptedException ex) {}

         try {
             thread.wait();
         threadWithExtends.wait();}
         catch
         (InterruptedException ex) {}




         threadWithExtends.notify();
         thread.notify();




    }
}
